export default {
  LOCATION_CHANGED: "LOCATION_CHANGED",
  ITEM_ADDED: "ITEM_ADDED"

  // USERS_RECEIVED: 'USERS_RECEIVED',
  // USER_CREATED: 'USER_CREATED',
  // USER_LOGGED_IN: 'USER_LOGGED_IN',
  // CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED'
};
